# Generated by Django 4.1.5 on 2023-01-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
